// <auto-generated />
namespace vuuvv.web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FixEndConferenceArticle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixEndConferenceArticle));
        
        string IMigrationMetadata.Id
        {
            get { return "201302251613261_FixEndConferenceArticle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
