// <auto-generated />
namespace vuuvv.web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FixConferenceArticle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixConferenceArticle));
        
        string IMigrationMetadata.Id
        {
            get { return "201302251605357_FixConferenceArticle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
