// <auto-generated />
namespace vuuvv.web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddActiveOrderingFieldsInCase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddActiveOrderingFieldsInCase));
        
        string IMigrationMetadata.Id
        {
            get { return "201304220846248_AddActiveOrderingFieldsInCase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
